server:
  port: 8100

spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, bagamao
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**

#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=yupi, swag
#            - AddRequestParameter=name, dog
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: yupi-fallback
#          uri: https://yupi.icu
#          predicates:
#              - Path=/fallback


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

dubbo:
  application:
    name: api-platform-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848